p8105_hw2_cy2751
================
Congyu Yang
2024-09-29

## Problem 1

``` r
NYCTransit_df <- read_csv(
  "datasets_hw2/NYC_Transit_Subway_Entrance_And_Exit_Data.csv",na = "",
  col_types = cols(Route8 = "c", Route9 = "c", Route10 = "c", Route11 = "c")) %>% 
  janitor::clean_names() %>% 
  select(line,station_name,station_latitude,station_longitude,(route1:route11),
         entry,exit_only,vending,entrance_type,ada) %>% 
  mutate(entry = ifelse(entry == "YES",T,F))
```

This dataset contains information of all train stations in NYC.
Including variables train line, station name, the specific location of
the station( latitude and longitude),all routes inside each station,
entry and exit information, vending information, entrance type and
whether ada compliance or not. I clean the data by importing data,
identify `NA` values, specify the variable type of all routes. I also
update variables names and select only the useful variables for the
later question. Lastly, update variable `entry` to be a logical
variable. Current dataset has dimension 1,868 × 20.  
We cannot say these data are tidy, because when we need to focus on
specific routes, routes should be a variable rather than a column
name.  

``` r
NYCTransit_df %>%  
  select(station_name, line) %>%  
  distinct() 
```

    ## # A tibble: 465 × 2
    ##    station_name             line    
    ##    <chr>                    <chr>   
    ##  1 25th St                  4 Avenue
    ##  2 36th St                  4 Avenue
    ##  3 45th St                  4 Avenue
    ##  4 53rd St                  4 Avenue
    ##  5 59th St                  4 Avenue
    ##  6 77th St                  4 Avenue
    ##  7 86th St                  4 Avenue
    ##  8 95th St                  4 Avenue
    ##  9 9th St                   4 Avenue
    ## 10 Atlantic Av-Barclays Ctr 4 Avenue
    ## # ℹ 455 more rows

There are 465 distinct stations.

``` r
NYCTransit_df %>% 
  select(station_name,line,ada) %>% 
  distinct() %>% 
  filter(ada == T) 
```

    ## # A tibble: 84 × 3
    ##    station_name                   line            ada  
    ##    <chr>                          <chr>           <lgl>
    ##  1 Atlantic Av-Barclays Ctr       4 Avenue        TRUE 
    ##  2 DeKalb Av                      4 Avenue        TRUE 
    ##  3 Pacific St                     4 Avenue        TRUE 
    ##  4 Grand Central                  42nd St Shuttle TRUE 
    ##  5 34th St                        6 Avenue        TRUE 
    ##  6 47-50th Sts Rockefeller Center 6 Avenue        TRUE 
    ##  7 Church Av                      6 Avenue        TRUE 
    ##  8 21st St                        63rd Street     TRUE 
    ##  9 Lexington Av                   63rd Street     TRUE 
    ## 10 Roosevelt Island               63rd Street     TRUE 
    ## # ℹ 74 more rows

In all, 84 stations are ADA compliant.

``` r
NYCTransit_df %>%
  filter(vending == "NO") %>% 
  pull(entry) %>% 
  mean()
```

    ## [1] 0.3770492

Around 37.7% of station entrances/exit with vending allow entrance.

``` r
NYCTransit_df %>% 
  pivot_longer(
    cols = route1:route11,
    names_to = "route_number",
    values_to = "route_name",
    names_prefix = "route"
  ) %>% 
  filter(route_name == "A") %>% 
  select(line,station_name) %>% 
    distinct()
```

    ## # A tibble: 60 × 2
    ##    line            station_name                 
    ##    <chr>           <chr>                        
    ##  1 42nd St Shuttle Times Square                 
    ##  2 8 Avenue        125th St                     
    ##  3 8 Avenue        145th St                     
    ##  4 8 Avenue        14th St                      
    ##  5 8 Avenue        168th St - Washington Heights
    ##  6 8 Avenue        175th St                     
    ##  7 8 Avenue        181st St                     
    ##  8 8 Avenue        190th St                     
    ##  9 8 Avenue        34th St                      
    ## 10 8 Avenue        42nd St                      
    ## # ℹ 50 more rows

``` r
NYCTransit_df %>% 
  pivot_longer(
    cols = route1:route11,
    names_to = "route_number",
    values_to = "route_name",
    names_prefix = "route"
  ) %>% 
  filter(route_name == "A") %>% 
  select(line,station_name,ada) %>% 
  distinct() %>% 
    filter(ada == T)
```

    ## # A tibble: 17 × 3
    ##    line             station_name                  ada  
    ##    <chr>            <chr>                         <lgl>
    ##  1 8 Avenue         14th St                       TRUE 
    ##  2 8 Avenue         168th St - Washington Heights TRUE 
    ##  3 8 Avenue         175th St                      TRUE 
    ##  4 8 Avenue         34th St                       TRUE 
    ##  5 8 Avenue         42nd St                       TRUE 
    ##  6 8 Avenue         59th St                       TRUE 
    ##  7 8 Avenue         Inwood - 207th St             TRUE 
    ##  8 8 Avenue         West 4th St                   TRUE 
    ##  9 8 Avenue         World Trade Center            TRUE 
    ## 10 Broadway         Times Square-42nd St          TRUE 
    ## 11 Broadway-7th Ave 59th St-Columbus Circle       TRUE 
    ## 12 Broadway-7th Ave Times Square                  TRUE 
    ## 13 Canarsie         8th Av                        TRUE 
    ## 14 Franklin         Franklin Av                   TRUE 
    ## 15 Fulton           Euclid Av                     TRUE 
    ## 16 Fulton           Franklin Av                   TRUE 
    ## 17 Rockaway         Howard Beach                  TRUE

60 distinct stations serve A train. Among these stations, 17 of them are
ADA compliant.

## Problem 2

``` r
Mr_Trash_df <- read_excel("datasets_hw2/202409 Trash Wheel Collection Data.xlsx",
                          sheet = "Mr. Trash Wheel",range = "A2:N653") %>% 
  janitor::clean_names() %>%
  mutate(sports_balls=as.integer(round(sports_balls))) %>% 
  mutate(year = as.numeric(year))

Professor_Trash_df <- read_excel("datasets_hw2/202409 Trash Wheel Collection Data.xlsx",
                          sheet = "Professor Trash Wheel",range = "A2:M120") %>% 
  janitor::clean_names()

Gwynnda_Trash_df <- read_excel("datasets_hw2/202409 Trash Wheel Collection Data.xlsx",
                          sheet = "Gwynnda Trash Wheel",range = "A2:L265") %>% 
  janitor::clean_names()

Mr_Trash_Bind <- Mr_Trash_df %>% mutate(name = "Mr_Trash") %>% 
  select(name,everything())

Professor_Trash_Bind <- Professor_Trash_df %>% mutate(name = "Professor_Trash") %>% 
  select(name,everything())

Gwynnda_Trash_Bind <- Gwynnda_Trash_df %>% mutate(name = "Gwynnda_Trash") %>% 
  select(name,everything())

(Whole_Trash_Bind <- bind_rows(Mr_Trash_Bind,Professor_Trash_Bind,Gwynnda_Trash_Bind) %>%
  select(-month,-year)) 
```

    ## # A tibble: 1,032 × 13
    ##    name     dumpster date                weight_tons volume_cubic_yards
    ##    <chr>       <dbl> <dttm>                    <dbl>              <dbl>
    ##  1 Mr_Trash        1 2014-05-16 00:00:00        4.31                 18
    ##  2 Mr_Trash        2 2014-05-16 00:00:00        2.74                 13
    ##  3 Mr_Trash        3 2014-05-16 00:00:00        3.45                 15
    ##  4 Mr_Trash        4 2014-05-17 00:00:00        3.1                  15
    ##  5 Mr_Trash        5 2014-05-17 00:00:00        4.06                 18
    ##  6 Mr_Trash        6 2014-05-20 00:00:00        2.71                 13
    ##  7 Mr_Trash        7 2014-05-21 00:00:00        1.91                  8
    ##  8 Mr_Trash        8 2014-05-28 00:00:00        3.7                  16
    ##  9 Mr_Trash        9 2014-06-05 00:00:00        2.52                 14
    ## 10 Mr_Trash       10 2014-06-11 00:00:00        3.76                 18
    ## # ℹ 1,022 more rows
    ## # ℹ 8 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, sports_balls <int>, homes_powered <dbl>

``` r
# remove month and year for tidy reason, date already includes such information
```

We combined three datasets: `Mr_Trash` dataset, `Professor_Trash`
dataset and `Gwynnda_Trash` dataset. Each contains information about
every dumpsters, including the date we collected data on, weight of
trash it deals with in ton, volume of trash and amount of each kind of
trash such as plastic bottles,polystyrene…. It is noteworthy that sports
ball is a unique trash that only exists in `Mr_Trash` dataset and there
is no glass bottle inside `Gwynnda_Trash` dataset.  
For `Mr_Trash` dataset, we collected information from 651 dumpsters;  

For `Professor_Trash` dataset, we collected information from 118
dumpsters;  

For `Gwynnda_Trash` dataset, we have information for 262 dumpsters,
while we have 263 pieces of information, it is because we have two rows
for dumpster 21, but on the different date;  

The final dataset has 1032 observations in total. For each observation,
we have 13 variables. We removed `month` and `year` variable in the
final dataset because these are redundant variables, we can also see
these information in `date` variable.  
We added a new column `name` to the final dataset, which indicates which
Trash Wheel does this dumpster come from.

``` r
Professor_Trash_df %>% select(weight_tons) %>% sum()
```

    ## [1] 246.74

The total weight of trash collected by Professor Trash Wheel is 246.74
tons.  

``` r
Gwynnda_Trash_df %>% 
  filter(month == "June", year == "2022") %>% 
  select(cigarette_butts) %>% 
  sum()
```

    ## [1] 18120

The total number of cigarette butts collected by Gwynnda in June of 2022
is 18120.  

## Problem 3

``` r
bakers <- read_csv("datasets_hw2/gbb_datasets/bakers.csv") %>% 
  janitor::clean_names()%>% 
  separate(baker_name,into = c("baker","last_name"),sep = " ")
```

    ## Rows: 120 Columns: 5
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (3): Baker Name, Baker Occupation, Hometown
    ## dbl (2): Series, Baker Age
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
bakes <- read_csv("datasets_hw2/gbb_datasets/bakes.csv") %>% 
  janitor::clean_names() %>% 
  mutate(baker=gsub('\"', '',baker))
```

    ## Rows: 548 Columns: 5
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (3): Baker, Signature Bake, Show Stopper
    ## dbl (2): Series, Episode
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
results <- read_csv("datasets_hw2/gbb_datasets/results.csv",skip =2) %>% 
  janitor::clean_names()%>% 
  mutate(
    baker = case_when(baker == "Joanne" ~ "Jo",TRUE ~ baker)
    )
```

    ## Rows: 1136 Columns: 5
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (2): baker, result
    ## dbl (3): series, episode, technical
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
anti_join(bakers,bakes,by = "baker")
```

    ## # A tibble: 22 × 6
    ##    baker  last_name       series baker_age baker_occupation             hometown
    ##    <chr>  <chr>            <dbl>     <dbl> <chr>                        <chr>   
    ##  1 Alice  Fevronia            10        28 Geography teacher            Essex   
    ##  2 Amelia LeBruin             10        24 Fashion designer             Halifax 
    ##  3 Antony Amourdoux            9        30 Banker                       London  
    ##  4 Briony Williams             9        33 Full-time parent             Bristol 
    ##  5 Dan    Beasley-Harling      9        36 Full-time parent             London  
    ##  6 Dan    Chambers            10        32 Support worker               Rotherh…
    ##  7 Helena Garcia              10        40 Online project manager       Leeds   
    ##  8 Henry  Bird                10        20 Student                      Durham  
    ##  9 Imelda McCarron             9        33 Countryside recreation offi… County …
    ## 10 Jamie  Finn                10        20 Part-time waiter             Surrey  
    ## # ℹ 12 more rows

``` r
anti_join(bakes,bakers,by = "baker")
```

    ## # A tibble: 0 × 5
    ## # ℹ 5 variables: series <dbl>, episode <dbl>, baker <chr>,
    ## #   signature_bake <chr>, show_stopper <chr>

``` r
anti_join(bakers, results, by = "baker")
```

    ## # A tibble: 0 × 6
    ## # ℹ 6 variables: baker <chr>, last_name <chr>, series <dbl>, baker_age <dbl>,
    ## #   baker_occupation <chr>, hometown <chr>

``` r
anti_join(results, bakers, by = "baker")
```

    ## # A tibble: 0 × 5
    ## # ℹ 5 variables: series <dbl>, episode <dbl>, baker <chr>, technical <dbl>,
    ## #   result <chr>

``` r
anti_join(bakes,results,by = "baker")
```

    ## # A tibble: 0 × 5
    ## # ℹ 5 variables: series <dbl>, episode <dbl>, baker <chr>,
    ## #   signature_bake <chr>, show_stopper <chr>

``` r
anti_join(results,bakes,by = "baker") # verify bakes has information only until series 8
```

    ## # A tibble: 220 × 5
    ##    series episode baker   technical result
    ##     <dbl>   <dbl> <chr>       <dbl> <chr> 
    ##  1      9       1 Antony         12 IN    
    ##  2      9       1 Briony          2 IN    
    ##  3      9       1 Dan             4 IN    
    ##  4      9       1 Jon             5 IN    
    ##  5      9       1 Karen           6 IN    
    ##  6      9       1 Kim-Joy        10 IN    
    ##  7      9       1 Luke            8 IN    
    ##  8      9       1 Rahul           7 IN    
    ##  9      9       1 Terry           9 IN    
    ## 10      9       1 Imelda         11 OUT   
    ## # ℹ 210 more rows

``` r
(results_and_bakers <- left_join(results,bakers,by = c("baker","series")))
```

    ## # A tibble: 1,136 × 9
    ##    series episode baker    technical result last_name baker_age baker_occupation
    ##     <dbl>   <dbl> <chr>        <dbl> <chr>  <chr>         <dbl> <chr>           
    ##  1      1       1 Annetha          2 IN     Mills            30 Midwife         
    ##  2      1       1 David            3 IN     Chambers         31 Entrepreneur    
    ##  3      1       1 Edd              1 IN     Kimber           24 Debt collector …
    ##  4      1       1 Jasmind…        NA IN     Randhawa         45 Assistant Credi…
    ##  5      1       1 Jonathan         9 IN     Shepherd         25 Research Analyst
    ##  6      1       1 Louise          NA IN     Brimelow         44 Police Officer  
    ##  7      1       1 Miranda          8 IN     Browne           37 Food buyer for …
    ##  8      1       1 Ruth            NA IN     Clemens          31 Retail manager/…
    ##  9      1       1 Lea             10 OUT    Harris           51 Retired         
    ## 10      1       1 Mark            NA OUT    Whithers         48 Bus Driver      
    ## # ℹ 1,126 more rows
    ## # ℹ 1 more variable: hometown <chr>

``` r
(bakers_all_info <- left_join(results_and_bakers,bakes,by = c("series","episode","baker")))
```

    ## # A tibble: 1,136 × 11
    ##    series episode baker    technical result last_name baker_age baker_occupation
    ##     <dbl>   <dbl> <chr>        <dbl> <chr>  <chr>         <dbl> <chr>           
    ##  1      1       1 Annetha          2 IN     Mills            30 Midwife         
    ##  2      1       1 David            3 IN     Chambers         31 Entrepreneur    
    ##  3      1       1 Edd              1 IN     Kimber           24 Debt collector …
    ##  4      1       1 Jasmind…        NA IN     Randhawa         45 Assistant Credi…
    ##  5      1       1 Jonathan         9 IN     Shepherd         25 Research Analyst
    ##  6      1       1 Louise          NA IN     Brimelow         44 Police Officer  
    ##  7      1       1 Miranda          8 IN     Browne           37 Food buyer for …
    ##  8      1       1 Ruth            NA IN     Clemens          31 Retail manager/…
    ##  9      1       1 Lea             10 OUT    Harris           51 Retired         
    ## 10      1       1 Mark            NA OUT    Whithers         48 Bus Driver      
    ## # ℹ 1,126 more rows
    ## # ℹ 3 more variables: hometown <chr>, signature_bake <chr>, show_stopper <chr>

``` r
(bakers_all_info_tidy <- 
    bakers_all_info %>%
    mutate(baker_name = str_c(baker,last_name,sep = " ")) %>% 
    select(series,episode,baker_name,
           signature_bake,show_stopper,technical,
           result,everything(),-baker,-last_name) %>% 
  filter(!is.na(result)))
```

    ## # A tibble: 710 × 10
    ##    series episode baker_name        signature_bake show_stopper technical result
    ##     <dbl>   <dbl> <chr>             <chr>          <chr>            <dbl> <chr> 
    ##  1      1       1 Annetha Mills     "Light Jamaic… Red, White …         2 IN    
    ##  2      1       1 David Chambers    "Chocolate Or… Black Fores…         3 IN    
    ##  3      1       1 Edd Kimber        "Caramel Cinn… N/A                  1 IN    
    ##  4      1       1 Jasminder Randha… "Fresh Mango … N/A                 NA IN    
    ##  5      1       1 Jonathan Shepherd "Carrot Cake … Three Tiere…         9 IN    
    ##  6      1       1 Louise Brimelow   "Carrot and O… Never Fail …        NA IN    
    ##  7      1       1 Miranda Browne    "Triple Layer… Three Tiere…         8 IN    
    ##  8      1       1 Ruth Clemens      "Three Tiered… Classic Cho…        NA IN    
    ##  9      1       1 Lea Harris        "Cranberry an… Raspberries…        10 OUT   
    ## 10      1       1 Mark Whithers     "Sticky Marma… Heart-shape…        NA OUT   
    ## # ℹ 700 more rows
    ## # ℹ 3 more variables: baker_age <dbl>, baker_occupation <chr>, hometown <chr>

**Describe your data cleaning process, including any questions you have
or choices you made. Briefly discuss the final dataset.**  
\*\* Not yet finished \*\*  

There are 23 bakers appears in `bakers` dataset but not inside `bakes`
dataset. It is because `bakes` only contains information from series 1 -
8, so it is reasonable that some bakers only exists in `bakers` dataset
but not inside `bakes` dataset. There is one exception: `"Jo"`, which
matches our result in checking bakers in `bakes` that are not in
`bakers`. We should remove the quotation mark for this cell in order for
it to match.  
By applying `anti_join` twice on `bakers` and `results`, we can see the
bakers `Joanne` may use her name `Jo` to apply for the competition, so
in datasets `bake` and `baker`, the name cannot match with the rows in
`results`. As we can see, the `series` information matches. We should do
data cleaning to solve this issue. For simplicity, we will change the
name in `results` dataset.  
After cleaning the data, we can see except for the `bakes` dataset only
have limit information, all other `auto_join` results becomes 0, which
means dataset can join perfectly with all information. Also remove all
OUT bakers from the further results for simplicity.(The last appearance
of each baker is at the time it OUT). Order matters, first combine which
one does matters!

``` r
write_csv(bakers_all_info_tidy, "datasets_hw2/gbb_datasets/bakers_all_info_tidy.csv")
```

``` r
bakers_all_info_tidy %>% 
  filter((result == "STAR BAKER"|result == "WINNER") & 
           (series == 5|series == 6|series == 7 |series == 8 
         |series ==9|series ==10)) %>% 
  select(series,episode,baker_name,technical,result)
```

    ## # A tibble: 60 × 5
    ##    series episode baker_name        technical result    
    ##     <dbl>   <dbl> <chr>                 <dbl> <chr>     
    ##  1      5       1 Nancy Birtwhistle         1 STAR BAKER
    ##  2      5       2 Richard Burr              1 STAR BAKER
    ##  3      5       3 Luis Troyano              2 STAR BAKER
    ##  4      5       4 Richard Burr              5 STAR BAKER
    ##  5      5       5 Kate Henry                3 STAR BAKER
    ##  6      5       6 Chetna Makan              2 STAR BAKER
    ##  7      5       7 Richard Burr              1 STAR BAKER
    ##  8      5       8 Richard Burr              4 STAR BAKER
    ##  9      5       9 Richard Burr              2 STAR BAKER
    ## 10      5      10 Nancy Birtwhistle         1 WINNER    
    ## # ℹ 50 more rows

\*\* Comment on this table – were there any predictable overall winners?
Any surprises? \*\*

\*\* Not yet finished \*\*  

``` r
viewership_df <- read_csv("datasets_hw2/gbb_datasets/viewers.csv") %>% 
  janitor::clean_names() %>% 
  pivot_longer(
    series_1:series_10,
    names_to = "series",
    names_prefix = "series_",
    values_to = "viewership"
  ) %>% 
  mutate(series = as.integer(series)) %>% 
  select(series,everything()) %>% 
  arrange(series,episode)
```

    ## Rows: 10 Columns: 11
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (11): Episode, Series 1, Series 2, Series 3, Series 4, Series 5, Series ...
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
viewership_df %>% head(n = 10)
```

    ## # A tibble: 10 × 3
    ##    series episode viewership
    ##     <int>   <dbl>      <dbl>
    ##  1      1       1       2.24
    ##  2      1       2       3   
    ##  3      1       3       3   
    ##  4      1       4       2.6 
    ##  5      1       5       3.03
    ##  6      1       6       2.75
    ##  7      1       7      NA   
    ##  8      1       8      NA   
    ##  9      1       9      NA   
    ## 10      1      10      NA

``` r
viewership_df %>% filter(series == 1) %>% 
  pull(viewership) %>% mean(na.rm = T)
```

    ## [1] 2.77

``` r
viewership_df %>% filter(series == 5) %>% 
  pull(viewership) %>% mean()
```

    ## [1] 10.0393

The average viewership in Season 1 is 2.77;  
And the average viewership in Season 5 is 10.0393.
